# Generated by Django 3.0.5 on 2020-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions1',
            fields=[
                ('question_id1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question1', models.TextField()),
                ('option1s', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='test1',
            fields=[
                ('test_id1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('theme1', models.CharField(max_length=100)),
                ('desc11', models.TextField()),
                ('noofstd', models.CharField(max_length=100)),
                ('start1', models.DateTimeField()),
                ('end1', models.DateTimeField()),
                ('qns', models.TextField()),
            ],
        ),
    ]
